CREATE DATABASE `api`;

CREATE TABLE `ci_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

/*Table structure for table `ci_users` */

CREATE TABLE `ci_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `firstname` VARCHAR(30) NOT NULL,
  `lastname` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `mobile_no` VARCHAR(30) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` TINYINT(4) NOT NULL DEFAULT '1',
  `is_active` TINYINT(4) NOT NULL DEFAULT '1',
  `is_admin` TINYINT(4) NOT NULL DEFAULT '0',
  `last_ip` VARCHAR(30) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

CREATE TABLE `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `token` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `expiry` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MYISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;